name: sut-se-price-map
networks:
  default:
    name: sut-se-price-map_default
services:
  db:
    build:
      context: db
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_DB: docker
      POSTGRES_PASSWORD: root
      POSTGRES_USER: docker
    healthcheck:
      interval: 1s
      retries: 10
      test:
        - CMD-SHELL
        - pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
    networks:
      default: null
    restart: always
    volumes:
      - source: db-data
        target: /var/lib/postgresql/data
        type: volume
        volume: {}
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        required: true
        restart: true
    environment:
      - CI_MODE=1
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "8080"
        target: 6969
volumes:
  db-data:
    name: sut-se-price-map_db-data
