services:
  web:
    build: .
    ports:
      - 8080:6969
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    build:
      context: db
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  db-data:
