name: Release

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-docker-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Generate Docker compose files
              run: |
                .docker/compose-config.sh
            - name: Docker image build test
              run: docker compose -f compose.ci.yaml build
