name: Release

on:
    push:
        branches:
            - master

jobs:
    test-docker-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Docker image build test
              run: docker-compose -f compose.ci.yml build